#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1234793120                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : cn                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file).
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/app-icon.png                        # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : 熊手纸样                                    # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                            # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : 投影仪裁切、拼接、打印、管理纸样，一个 App 全搞定。

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Panda Pattern
your_link                                 : https://pandapattern.com
your_city                                 : Beijing
email_address                             :
linkedin_username                         :
linkedin_company                          :                                           
facebook_username                         :                                           
instagram_username                        :
twitter_username                          :
github_username                           :
youtube_username                          :
mastodon_link                             :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : 投影仪裁切
    description                           : 手机连接投影仪，数字精确校准，将纸样以实际尺寸投影到面料上，直接裁切，大幅简化裁切流程。
    fontawesome_icon_name                 : magic
    
  - title                                 : 纸样存储
    description                           : 支持 PDF / PLT / SVG 格式的纸样存储和预览。按款式、格式进行分类管理，让纸样更加清晰有序，易于查找。
    fontawesome_icon_name                 : mobile

  - title                                 : 纸样拼接
    description                           : 将小尺寸 A4 / A3 / US Letter 纸张拼接成一整张大尺寸纸样。支持小尺寸纸样拼接后投影仪裁切。
    fontawesome_icon_name                 : file-pdf

  - title                                 : 纸样打印
    description                           : 支持将大尺寸纸样裁切为小尺寸 A4、A3、US Letter 纸张打印。支持 AirPrint，手机直接打印。
    fontawesome_icon_name                 : print

  - title                                 : 缝纫社区
    description                           : 加入缝纫社区，和同好分享交流，帮助你找到适合的纸样、教程、设计师和面辅料供应商。
    fontawesome_icon_name                 : link

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.jpg            # Replace with alternative image path or image URL.
cover_overlay_color                       : "#161b1d"
cover_overlay_transparency                : 0.5

device_color                              : yellow                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#ffc403"
feature_text_color                        : "#555555"

feature_icons_foreground_color            : "#ffc403"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#555555"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
